Iteracija 0, polariter positivan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasa5\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


0


Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Map:   0%|          | 0/11895 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTPOS0 into local empty directory.


Download file pytorch_model.bin:   0%|          | 16.5k/2.88G [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/2.88G [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...


Push attempt 1 failed with error: File SRGPTSENTPOS0\pytorch_model.bin cannot be opened.


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 9d0a210259a9102e02edf406bcd40228742272f4 but expected 9f1122c97acb3f471f5384fed2196934d3100389        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Push attempt 2 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 9d0a210259a9102e02edf406bcd40228742272f4 but expected 9f1122c97acb3f471f5384fed2196934d3100389        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/SRGPTSENTPOS0
   9d0a210..814b67a  main -> main



Max memory allocated by tensors:
6.42 GB


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4920    0]
 [  37    0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4920
           1       0.00      0.00      0.00        37

    accuracy                           0.99      4957
   macro avg       0.50      0.50      0.50      4957
weighted avg       0.99      0.99      0.99      4957



C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
The push command with PID 22576

Iteracija 0, polariter negativan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasa5\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


0


Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Map:   0%|          | 0/11895 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTNEG0 into local empty directory.


Download file pytorch_model.bin:   0%|          | 15.4k/2.88G [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

To https://huggingface.co/Tanor/SRGPTSENTNEG0
   859207f..65b73c2  main -> main

To https://huggingface.co/Tanor/SRGPTSENTNEG0
   65b73c2..3abb7d9  main -> main

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Max memory allocated by tensors:
6.42 GB
[[4882   21]
 [  26   28]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4903
           1       0.57      0.52      0.54        54

    accuracy                           0.99      4957
   macro avg       0.78      0.76      0.77      4957
weighted avg       0.99      0.99      0.99      4957



Iteracija 2, polariter positivan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

0


Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Map:   0%|          | 0/11895 [00:00<?, ? examples/s]

C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\SRGPTSENTPOS0 is already a clone of https://huggingface.co/Tanor/SRGPTSENTPOS0. Make sure you pull the latest changes with `repo.git_pull()`.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\check

Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 77ab5368bb81bab98c526a9e4c43d734e3c4fb34 but expected fd98c2bac3ae794a305ff3e794fcf25820181e49        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 77ab5368bb81bab98c526a9e4c43d734e3c4fb34 but expected fd98c2bac3ae794a305ff3e794fcf25820181e49        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/SRGPTSENTPOS0
   77ab536..448f2b3  main -> main



Max memory allocated by tensors:
6.42 GB


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4907   13]
 [  28    9]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4920
           1       0.41      0.24      0.31        37

    accuracy                           0.99      4957
   macro avg       0.70      0.62      0.65      4957
weighted avg       0.99      0.99      0.99      4957



In [ ]:
%run trainSRGPT.py

In [ ]:
%run trainSRGPT.py

In [ ]:
trainer.push_to_hub()

In [ ]:
%run trainSRGPT.py